call run_compare_file.bat 1
call run_compare_file.bat 2
call run_compare_file.bat 3
call run_compare_file.bat 4
call run_compare_file.bat 5
call run_compare_file.bat 6
call run_compare_file.bat 7
call run_compare_file.bat 8
call run_compare_file.bat 9
call run_compare_file.bat 10
call run_compare_file.bat 11
call run_compare_file.bat 12
call run_compare_file.bat 13
call run_compare_file.bat 14
call run_compare_file.bat 15
call run_compare_file.bat 16
call run_compare_file.bat 17
call run_compare_file.bat 18
call run_compare_file.bat 19
call run_compare_file.bat 20
call run_compare_file.bat 21
call run_compare_file.bat 22
call run_compare_file.bat 23
call run_compare_file.bat 24
call run_compare_file.bat 25
call run_compare_file.bat 26
call run_compare_file.bat 27
call run_compare_file.bat 28
call run_compare_file.bat 29
call run_compare_file.bat 30
call run_compare_file.bat 31
call run_compare_file.bat 32
call run_compare_file.bat 33
call run_compare_file.bat 34
call run_compare_file.bat 35
call run_compare_file.bat 36
call run_compare_file.bat 37
call run_compare_file.bat 38
call run_compare_file.bat 39
call run_compare_file.bat 40
call run_compare_file.bat 41
call run_compare_file.bat 42
call run_compare_file.bat 43
call run_compare_file.bat 44
call run_compare_file.bat 45
call run_compare_file.bat 46
call run_compare_file.bat 47
call run_compare_file.bat 48
call run_compare_file.bat 49
call run_compare_file.bat 50
call run_compare_file.bat 51
call run_compare_file.bat 52
call run_compare_file.bat 53
call run_compare_file.bat 54
call run_compare_file.bat 55
call run_compare_file.bat 56
call run_compare_file.bat 57
call run_compare_file.bat 58
call run_compare_file.bat 59
call run_compare_file.bat 60
call run_compare_file.bat 61
call run_compare_file.bat 62
call run_compare_file.bat 63
call run_compare_file.bat 64
call run_compare_file.bat 65
call run_compare_file.bat 66
call run_compare_file.bat 67
call run_compare_file.bat 68
call run_compare_file.bat 69
call run_compare_file.bat 70
call run_compare_file.bat 71
call run_compare_file.bat 72
call run_compare_file.bat 73
call run_compare_file.bat 74
call run_compare_file.bat 75
call run_compare_file.bat 76
call run_compare_file.bat 77
call run_compare_file.bat 78
call run_compare_file.bat 79
call run_compare_file.bat 80
call run_compare_file.bat 81
call run_compare_file.bat 82
call run_compare_file.bat 83
call run_compare_file.bat 84
call run_compare_file.bat 85
call run_compare_file.bat 86
call run_compare_file.bat 87
call run_compare_file.bat 88
call run_compare_file.bat 89
call run_compare_file.bat 90
call run_compare_file.bat 91
call run_compare_file.bat 92
call run_compare_file.bat 93
call run_compare_file.bat 94
call run_compare_file.bat 95
call run_compare_file.bat 96
call run_compare_file.bat 97
call run_compare_file.bat 98
call run_compare_file.bat 99
call run_compare_file.bat 100
call run_compare_file.bat 101
call run_compare_file.bat 102
call run_compare_file.bat 103
call run_compare_file.bat 104
call run_compare_file.bat 105
call run_compare_file.bat 106
call run_compare_file.bat 107
call run_compare_file.bat 108
call run_compare_file.bat 109
call run_compare_file.bat 110
