hqlcs "SELECT field1 FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(field1) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1 FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(field1) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, sum(field1) FROM 'a.a'"
hqlcs "SELECT field1, len(sum(field1)) FROM 'a.a'"
hqlcs "SELECT field1, sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(field1) FROM 'a.a'"
hqlcs "SELECT len(field1), len(sum(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT sum(field1), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(sum(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT sum(len(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1 FROM 'a.a' WHERE field1 > 0 GROUP BY field2"
hqlcs "SELECT len(field1) FROM 'a.a' WHERE field1 > 0 GROUP BY field2"
hqlcs "SELECT len(len(field1)) FROM 'a.a' WHERE field1 > 0 GROUP BY field2"
hqlcs "SELECT field1 FROM 'a.a' WHERE field1 > 0 HAVING sum(field1) > 0"
hqlcs "SELECT len(field1) FROM 'a.a' WHERE field1 > 0 HAVING sum(field1) > 0"
hqlcs "SELECT len(len(field1)) FROM 'a.a' WHERE field1 > 0 HAVING sum(field1) > 0"
hqlcs "SELECT field1 FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT len(field1) FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT sum(field1) FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT len(sum(field1)) FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT sum(len(field1)) FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT len(len(field1)) FROM 'a.a' GROUP BY field2 ORDER BY field1"
hqlcs "SELECT field1 FROM 'a.a' GROUP BY field2 HAVING sum(field1) > 0"
hqlcs "SELECT len(field1) FROM 'a.a' GROUP BY field2 HAVING sum(field1) > 0"
hqlcs "SELECT len(len(field1)) FROM 'a.a' GROUP BY field2 HAVING sum(field1) > 0"
hqlcs "SELECT field1 FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT len(field1) FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT sum(field1) FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT len(sum(field1)) FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT sum(len(field1)) FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT len(len(field1)) FROM 'a.a' ORDER BY field1 HAVING sum(field1) > 0"
hqlcs "SELECT field1, sum(field1) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT field1, len(sum(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT field1, sum(len(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT len(field1), sum(field1) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT len(field1), len(sum(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT len(field1), sum(len(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT sum(field1), len(len(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT len(sum(field1)), len(len(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT sum(len(field1)), len(len(field1)) FROM 'a.a' WHERE field1 > 0"
hqlcs "SELECT field1, len(field1) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1, sum(field1) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1, len(sum(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1, sum(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1, len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(field1), sum(field1) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(field1), len(sum(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(field1), sum(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(field1), len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT sum(field1), len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT len(sum(field1)), len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT sum(len(field1)), len(len(field1)) FROM 'a.a' GROUP BY field2"
hqlcs "SELECT field1, sum(field1) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT field1, len(sum(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT field1, sum(len(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT len(field1), sum(field1) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT len(field1), len(sum(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT len(field1), sum(len(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT sum(field1), len(len(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT len(sum(field1)), len(len(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT sum(len(field1)), len(len(field1)) FROM 'a.a' ORDER BY field1"
hqlcs "SELECT field1, len(field1) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, sum(field1) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, len(sum(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, sum(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(field1), sum(field1) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(field1), len(sum(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(field1), sum(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(field1), len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT sum(field1), len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT len(sum(field1)), len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT sum(len(field1)), len(len(field1)) FROM 'a.a' HAVING sum(field1) > 0"
hqlcs "SELECT field1, len(field1), sum(field1) FROM 'a.a'"
hqlcs "SELECT field1, len(field1), len(sum(field1)) FROM 'a.a'"
hqlcs "SELECT field1, len(field1), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1, sum(field1), len(sum(field1)) FROM 'a.a'"
hqlcs "SELECT field1, sum(field1), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1, sum(field1), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1, len(sum(field1)), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1, len(sum(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT field1, sum(len(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(field1), len(sum(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(field1), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(field1), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), len(sum(field1)), sum(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), len(sum(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(field1), sum(len(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT sum(field1), len(sum(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT sum(field1), sum(len(field1)), len(len(field1)) FROM 'a.a'"
hqlcs "SELECT len(sum(field1)), sum(len(field1)), len(len(field1)) FROM 'a.a'"
